name: Auto Sync

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    # Run every hour
    - cron: '0 * * * *'
  workflow_dispatch:

permissions:
  contents: write
jobs:
  sync:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Configure Git
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
    
    - name: Sync changes
      run: |
        git fetch origin
        git pull origin main --rebase
        
        # Check if there are any changes to push
        if git diff --quiet HEAD origin/main; then
          echo "No changes to sync"
        else
          echo "Syncing changes..."
          git push origin main
        fi
    
    - name: Auto-commit any new changes
      run: |
        # Add any untracked files
        git add .
        
        # Check if there are changes to commit
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          echo "Committing new changes..."
          git commit -m "Auto-sync: Update files $(date '+%Y-%m-%d %H:%M:%S')"
          git push origin main
        fi